apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-manifests-deployer-job
spec:
  template:
    spec:
      containers:
      - name: deployer-container
        image: asia-northeast3-docker.pkg.dev/fligh7/fligh7-image/yoisakikanade/fligh7:${currentBuild.number}
        # 여기에 필요한 환경 변수, 볼륨 마운트 등을 추가할 수 있습니다.
      restartPolicy: Never
